AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'

Parameters:
  AppId:
    Type: String

Resources:
  snsPayloadLoggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/sns-payload-logger.snsPayloadLoggerHandler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 60
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        SimpleTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref SimpleTopic
  SimpleTopic:
    Type: AWS::SNS::Topic